universe = parallel

executable = openmpiscript.sh

should_transfer_files = YES

#arguments = KMEANS_mpi test_files/input100D2.inp 15 1000 1 1 mpi/out100D2.txt

#transfer_input_files = test_files, KMEANS_mpi, mpi

when_to_transfer_output = on_exit_or_evict

#output = mpi/out.$(NODE)_$(Process)
#error = mpi/err.$(NODE)_$(Process)
#log = mpi/log

machine_count = 1
#request_cpus = 32

getenv = True

queue
